### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [penguintrace/penguintrace#1]
Desc
-
when building it on Ubuntu 18.04, using make command

Message
-

 [ CXX] debug/Compiler.cpp
  [ CXX] object/Section.cpp
  [ CXX] object/Symbol.cpp
  [ CXX] object/ParserFactory.cpp
  [ CXX] object/ElfParser.cpp
  [ CXX] object/Parser.cpp
  [ CXX] object/Disassembler.cpp
  [ CXX] object/LLVMParser.cpp
  [ CXX] object/LineDisassembly.cpp
  [ CXX] dwarf/DIETraversal.cpp
  [ CXX] dwarf/DIEValue.cpp
  [ CXX] dwarf/DIE.cpp
  [ CXX] dwarf/Frame.cpp
  [ CXX] dwarf/Abbrev.cpp
  [ CXX] dwarf/DIEPrint.cpp
  [ CXX] dwarf/Info.cpp
  [ CXX] dwarf/AttrValue.cpp
  [ CXX] dwarf/LineProgram.cpp
  [ CXX] x86_64/Stepper.cpp
  [ CXX] x86_64/Arch.cpp
  [ CXX] capabilities/enabled/Stepper.cpp
capabilities/enabled/Stepper.cpp:32:10: fatal error: 'sys/capability.h' file not
      found
#include <sys/capability.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:119: recipe for target 'build/capabilities/enabled/Stepper.o' failed
make: *** [build/capabilities/enabled/Stepper.o] Error 1

**Comment by martiansoup** [comment]
Hi,

If building penguinTrace with capability support (which is enabled by default) then the `libcap-dev` package is needed on Ubuntu (or derived distros). The 'Prerequisites' section in the readme provides more details of other dependencies.

Thanks,
Alex
